export const SUB_FILTER_DATA = {
  region: ['Europe', 'Oceania', 'Americas', 'Asia', 'Africa', 'Antarctic'],
  subregion: [
    'Southeast Europe',
    'Western Europe',
    'Northern Europe',
    'Southern Europe',
    'Eastern Europe',
    'Central Europe',
    'Polynesia',
    'Micronesia',
    'Melanesia',
    'Australia and New Zealand',
    'South-Eastern Asia',
    'Eastern Asia',
    'Central Asia',
    'Western Asia',
    'Southern Asia',
    'Western Africa',
    'Eastern Africa',
    'Northern Africa',
    'Southern Africa',
    'Middle Africa',
    'Caribbean',
    'South America',
    'North America',
    'Central America',
  ],
}

export const FILTER_DATA = ['All', 'Region', 'Subregion']
